# run: echidna-parade ./ --contract ReBakedDAO --config echidna.config.yaml --timeout 60 
testMode: assertion
testLimit: 5000
timeout: 300 
seqLen: 2
stopOnFail: True
corpusDir: "corpus-assertion"
solcArgs: "--allow-paths /home/phong_ho/NAPA/buildsmartcontract/node_modules"