name: Echidna Fuzzer
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 14.18.2
        cache: 'npm'

    - name: Install dependencies
      run: |
        cp .env.dev .env
        npm ci --force

    - name: Compile contracts
      run: npx hardhat compile

    - name: Run Echidna
      uses: crytic/echidna-action@v2
      with:
        solc-version: 0.8.16
        files: .
        contract: ReBakedDAO
        test-mode: exploration
        crytic-args: --hardhat-ignore-compile

      